---
# --------------------------------------------------
# Create user/group
# --------------------------------------------------
- name: "Add miarec_livemon group '{{ miarec_livemon_bin_group }}'"
  group:
    name: "{{ miarec_livemon_bin_group }}"
    state: present
  when: miarec_livemon_bin_group != 'root'

- name: "Add miarec_livemon user '{{ miarec_livemon_bin_user }}'"
  user:
    name: "{{ miarec_livemon_bin_user }}"
    group: "{{ miarec_livemon_bin_group }}"
    comment: "MiaRec"
    shell: /bin/false
    system: yes
  when: miarec_livemon_bin_user != 'root'

# --------------------------------------------------
# Initialize the installation/upgrade process
# --------------------------------------------------
- name: Initialize the deploy root and gather facts
  deploy_helper:
    path: "{{ miarec_livemon_install_dir }}"
    release: "{{ miarec_livemon_version }}"
    mode: u=rwX,g=rX,o=rX
  become: true

# --------------------------------------------------
# Install/upgrade 'miarec' app files
# --------------------------------------------------
- include: install.yml
  become: true

# --------------------------------------------------
# Cleanup old and unfinished releases
# --------------------------------------------------
- name: Cleanup old releases
  deploy_helper:
    path: "{{ miarec_livemon_install_dir }}"
    release: '{{ deploy_helper.new_release }}'
    state: finalize
    keep_releases: 10
  notify: 
    - restart miarec_livemon
  become: true
