---
- name: Restart miarec_livemon
  service:
    name: miarec_livemon
    state: restarted
  become: true

- name: Start miarec_livemon
  service:
    name: miarec_livemon
    state: started
  become: true

- name: Reload miarec_livemon
  service:
    name: miarec_livemon
    state: restarted
  become: true
